"""Flutter and Dart verification adapters.

Both ecosystems share the same manifest file (``pubspec.yaml``).
``FlutterAdapter`` is checked first in ``ADAPTER_PRECEDENCE`` and only
matches when ``pubspec.yaml`` actually declares the Flutter SDK dependency,
so a plain Dart package is never misidentified as Flutter and vice versa.

Neither adapter ever matches based on nested ``android/`` or ``ios/`` build
files alone -- those are platform scaffolding generated by `flutter create`
and owned by the Flutter project, not independent Java/Gradle projects. The
containment logic that keeps them from being reported as separate projects
in a multi-project repository lives in
``app.services.verification.project_analyzer``.
"""

import re
from pathlib import Path
from typing import ClassVar, Dict, List, Optional

from app.services.verification.base import VerificationAdapter

_FLUTTER_SDK_PATTERN = re.compile(r"flutter\s*:\s*\n\s*sdk\s*:\s*flutter", re.MULTILINE)
_LOOSE_FLUTTER_SDK_PATTERN = re.compile(r"^\s*sdk\s*:\s*flutter\s*$", re.MULTILINE)


def _read_pubspec(workspace: Path) -> str:
    pubspec = workspace / "pubspec.yaml"
    try:
        return pubspec.read_text(encoding="utf-8", errors="ignore")
    except Exception:
        return ""


def _is_flutter_project(workspace: Path) -> bool:
    text = _read_pubspec(workspace)
    if not text:
        return False
    return bool(_FLUTTER_SDK_PATTERN.search(text) or _LOOSE_FLUTTER_SDK_PATTERN.search(text))


def _has_dart_tests(workspace: Path) -> bool:
    test_dir = workspace / "test"
    return test_dir.is_dir() and any(test_dir.rglob("*_test.dart"))


def _parse_dart_test_output(output: str, returncode: int) -> Dict[str, int]:
    """Parse `flutter test` / `dart test` console output.

    Its reporter streams cumulative progress lines like ``00:03 +5: ...`` or,
    on failure, ``00:05 +3 -2: some tests failed.`` -- the LAST such line
    carries the final tally, so all matches are scanned and the last one
    wins rather than the first.
    """
    matches = re.findall(r"\+(\d+)(?:\s*-(\d+))?:", output)
    if matches:
        passed_str, failed_str = matches[-1]
        return {"passed": int(passed_str), "failed": int(failed_str) if failed_str else 0}
    if "No issues found!" in output:
        return {"passed": 1, "failed": 0}
    return {"passed": 1, "failed": 0} if returncode == 0 else {"passed": 0, "failed": 1}


class FlutterAdapter(VerificationAdapter):
    ecosystem: ClassVar[str] = "flutter"
    manifest_files: ClassVar[List[str]] = ["pubspec.yaml"]

    @classmethod
    def detect(cls, workspace: Path) -> bool:
        return (workspace / "pubspec.yaml").is_file() and _is_flutter_project(workspace)

    def install_command(self, workspace: Path) -> Optional[List[str]]:
        return ["flutter", "pub", "get"]

    def test_command(self, workspace: Path, test_path: Optional[str] = None) -> Optional[List[str]]:
        if test_path or _has_dart_tests(workspace):
            cmd = ["flutter", "test"]
            if test_path:
                cmd.append(test_path)
            return cmd
        # No test/ directory -- `flutter analyze` is still a meaningful,
        # non-guessed verification signal (mirrors Node's build fallback).
        return ["flutter", "analyze"]

    def parse_output(self, output: str, returncode: int) -> Dict[str, int]:
        return _parse_dart_test_output(output, returncode)


class DartAdapter(VerificationAdapter):
    """Pure Dart package: pubspec.yaml present, but without a Flutter SDK
    dependency (checked via FlutterAdapter first in ADAPTER_PRECEDENCE)."""

    ecosystem: ClassVar[str] = "dart"
    manifest_files: ClassVar[List[str]] = ["pubspec.yaml"]

    @classmethod
    def detect(cls, workspace: Path) -> bool:
        return (workspace / "pubspec.yaml").is_file() and not _is_flutter_project(workspace)

    def install_command(self, workspace: Path) -> Optional[List[str]]:
        return ["dart", "pub", "get"]

    def test_command(self, workspace: Path, test_path: Optional[str] = None) -> Optional[List[str]]:
        if test_path or _has_dart_tests(workspace):
            cmd = ["dart", "test"]
            if test_path:
                cmd.append(test_path)
            return cmd
        return ["dart", "analyze"]

    def parse_output(self, output: str, returncode: int) -> Dict[str, int]:
        return _parse_dart_test_output(output, returncode)
